create database en70044_9;
use en70044_9;
CREATE TABLE PRODUCT(
ID_PRODUCT INT IDENTITY PRIMARY KEY,
NAME VARCHAR(40),
PRICE FLOAT);
CREATE TABLE ORDERS(
ID_ORDERS INT IDENTITY PRIMARY KEY,
ID_PRODUCT INT,
ID_CUSTOMER INT,
NO_OF_PRODUCT FLOAT,
DATE_TIME TIME);

CREATE TABLE STORAGE(
ID_STORAGE INT IDENTITY PRIMARY KEY,
ID_PRODUCT INT,
NO_OF_PRODUCT_IN_STORAGE FLOAT,
DATE_TIME TIME);

CREATE TABLE STORAGE_MOVE(
ID_STORAGE_MOVE INT IDENTITY PRIMARY KEY,
ID_STORAGE INT,
ID_PRODUCT INT,
NO_OF_PRODUCT_IN_STORAGE INT,
DATE_TIME TIME);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ID_PRODUCT_ORDERS
FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)

ALTER TABLE STORAGE
ADD CONSTRAINT FK_ID_PRODUCT_STORAGE
FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)

UPDATE STORAGE SET DATE_TIME=GETDATE()
INSERT INTO STORAGE(ID_PRODUCT,NO_OF_PRODUCT_IN_STORAGE)
VALUES(1,1000);

INSERT INTO STORAGE(ID_PRODUCT,NO_OF_PRODUCT_IN_STORAGE)
VALUES(2,1000);
